// ===============================================================
//  Alert.js
//  Mongoose schema for user notifications and spending breach
//  warnings generated by the automated cron engine.
// ===============================================================

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  category: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Category',
    // Optional: Some alerts might be system-wide rather than category-specific
  },
  type: {
    type: String,
    enum: ['info', 'warning', 'critical'],
    required: true,
  },
  message: {
    type: String,
    required: true,
  },
  isRead: {
    type: Boolean,
    default: false,
  }
}, { timestamps: true });

module.exports = mongoose.model('Alert', alertSchema);
